### ISSUE TITLE
about real data

### ISSUE THREAD

**Issue by xiahaa** [sebhaner/refractive_pose#1]
Hi, thanks for sharing your code. 
May I ask you if the "Rubik’s cube" data can be accessed online? 

Best

**Comment by sebhaner** [comment]
Hi, no that data was never posted online. I had a look around and I did find the original images and points, but I can only provide them "as is", if you want to use them you'll have to figure out how yourself (sorry).

https://drive.google.com/file/d/11sOV1LsU__DDFvO9rJT9AYWvdxfUuij6/view?usp=sharing

**Comment by xiahaa** [comment]
> Hi, no that data was never posted online. I had a look around and I did find the original images and points, but I can only provide them "as is", if you want to use them you'll have to figure out how yourself (sorry).
> 
> https://drive.google.com/file/d/11sOV1LsU__DDFvO9rJT9AYWvdxfUuij6/view?usp=sharing

Thanks for your kindly reply and sharing of your data.
I think I know how to use it. But just one more question, 
in the script, there is a line `load ../images/cdopt.mat`.
It seems the `cdopt.mat` is located in a folder one layer above the `images` folder.
I am not sure if you could find this mat file or not. If yes, then it would be nice.

Best

**Comment by sebhaner** [comment]
That just contains the intrinsic parameters for the camera
`      2478.00578698
       2493.12551695
       1295.09153568
        961.44127323
          0.17182780
         -0.66946834
          0.00080807
         -0.00117258
          1.00171486
          0.00037273
`
It should be in order `cd = [f_x f_y c_x c_y k1 k2 tan1 tan2 k3 skew]` but looks wrong, maybe k3 and skew are switched, I don't know.

**Comment by xiahaa** [comment]
> That just contains the intrinsic parameters for the camera ` 2478.00578698 2493.12551695 1295.09153568 961.44127323 0.17182780 -0.66946834 0.00080807 -0.00117258 1.00171486 0.00037273` It should be in order `cd = [f_x f_y c_x c_y k1 k2 tan1 tan2 k3 skew]` but looks wrong, maybe k3 and skew are switched, I don't know.

Thank you very much.
I make it work now. 
Just close this issue.
Thanks again.
